import wx
class myframe(wx.Frame):
    def __init__(self):
        wx.Frame.__init__(self,None,-1,'my gui')
        self.panel=wx.Panel(self,-1)
        self.panel1=wx.Panel(self.panel,-1)
        self.panel2=wx.Panel(self.panel,-1)
        self.sizer=wx.BoxSizer(wx.HORIZONTAL)
        self.sizer1=wx.BoxSizer(wx.VERTICAL)
        self.sizer2=wx.BoxSizer(wx.VERTICAL)
        self.text1=wx.StaticText(self.panel1,-1,'one')
        self.text2=wx.StaticText(self.panel1,-1,'two')
        self.text3=wx.StaticText(self.panel1,-1,'three')
        self.sizer1.Add(self.text1,proportion=1,flag=wx.CENTER|wx.TOP|wx.RIGHT|wx.EXPAND,border=20)
        self.sizer1.Add(self.text2, proportion=1, flag=wx.CENTER|wx.TOP | wx.RIGHT | wx.EXPAND, border=20)
        self.sizer1.Add(self.text3, proportion=1, flag=wx.CENTER|wx.TOP | wx.RIGHT | wx.EXPAND, border=20)
        self.panel1.SetSizer(self.sizer1)
        self.text4 = wx.StaticText(self.panel2, -1, 'AAAAAAAAAAAAAAAAAAAA')
        self.text5 = wx.StaticText(self.panel2, -1, 'BBBBBBBBBBBBBBBBBBBB')
        self.text6 = wx.StaticText(self.panel2, -1, 'CCCCCCCCCCCCCCCCCCCC')
        self.text7 = wx.StaticText(self.panel2, -1, 'DDDDDDDDDDDDDDDDDDDD')
        self.text8 = wx.StaticText(self.panel2, -1, 'EEEEEEEEEEEEEEEEEEEE')
        self.text9 = wx.StaticText(self.panel2, -1, 'FFFFFFFFFFFFFFFFFFFF')
        self.sizer2.Add(self.text4, proportion=1, flag=wx.CENTER|wx.TOP | wx.RIGHT | wx.EXPAND, border=20)
        self.sizer2.Add(self.text5, proportion=1, flag=wx.CENTER|wx.TOP | wx.RIGHT | wx.EXPAND, border=20)
        self.sizer2.Add(self.text6, proportion=1, flag=wx.CENTER|wx.TOP | wx.RIGHT | wx.EXPAND, border=20)
        self.sizer2.Add(self.text7, proportion=1, flag=wx.CENTER|wx.TOP | wx.RIGHT | wx.EXPAND, border=20)
        self.sizer2.Add(self.text8, proportion=1, flag=wx.CENTER|wx.TOP | wx.RIGHT | wx.EXPAND, border=20)
        self.sizer2.Add(self.text9, proportion=1, flag=wx.CENTER|wx.TOP | wx.RIGHT | wx.EXPAND, border=20)
        self.panel2.SetSizer(self.sizer2)
        self.sizer.Add(self.panel1, proportion=1,flag=wx.CENTER|wx.RIGHT|wx.LEFT,border=30)
        self.sizer.Add(self.panel2, proportion=1,flag=wx.CENTER|wx.RIGHT|wx.LEFT,border=30)
        self.panel.SetSizer(self.sizer)

app=wx.App()
frame=myframe()
frame.Show()
app.MainLoop()